"""Каталог правил аудита сетевых устройств (Cisco IOS / Junos) — перенесено
из NetOpsHub (hub/backend/app/modules/compliance_audit/rules.py +
app/config_analysis.py, слитые в network_audit_facts.py), только для
вендоров, которые есть в GridForge (app.models.Vendor).

Баллы — фиксированная шкала по severity (risk_scoring.POINTS_BY_SEVERITY),
тот же принцип, что и в ad_audit_rules.py: критично весит сильно больше,
чтобы одно критичное нарушение уже подняло риск-скор категории к верхней
границе."""

from __future__ import annotations

from app.risk_scoring import Rule

CATALOG_VERSION = "1.1"
CATALOG_UPDATED_AT = "2026-09-15"

CAT_ACCESS = "Управление и доступ"
CAT_L3 = "Резервирование (L3)"
CAT_L2 = "L2-доступ"
CAT_HYGIENE = "Гигиена конфигурации"


RULES: list[Rule] = [
    # --- Управление и доступ ---
    Rule("A0", CAT_ACCESS, "critical",
         "Управляется только по Telnet",
         "Узел добавлен с вендором cisco_ios_telnet — весь трафик управления (включая пароли) передаётся открытым текстом.",
         "Включить SSH на устройстве (ip domain-name + crypto key generate rsa + transport input ssh) и переключить узел на вендор cisco_ios.",
         lambda f: not f.get("managed_via_telnet", False),
         applies=lambda f: f.get("managed_via_telnet", False)),
    Rule("A1", CAT_ACCESS, "critical",
         "AAA не подключён к центральному серверу",
         "Не найдено aaa new-model (Cisco) / authentication-order (Junos) — доступ только по локальным учёткам.",
         "Cisco: aaa new-model + aaa authentication login со ссылкой на group tacacs+. Junos: set system authentication-order [tacplus password].",
         lambda f: f["aaa_configured"],
         objects=lambda f: [f"Локальная учётка: {u}" for u in f.get("local_usernames", [])]),
    Rule("A2", CAT_ACCESS, "critical",
         "Telnet разрешён на VTY (или transport input не ограничен)",
         "На VTY-линиях явно разрешён Telnet, либо transport input не задан вовсе — по умолчанию IOS разрешает и Telnet.",
         "Cisco: transport input ssh на всех line vty.",
         lambda f: f["vty_ssh_only"],
         objects=lambda f: list(f.get("vty_telnet_raw", []))),
    Rule("A3", CAT_ACCESS, "medium",
         "Таймаут неактивной сессии не задан",
         "exec-timeout / idle-timeout не найден на VTY/консоли — сессия может висеть открытой бессрочно.",
         "Cisco: exec-timeout 10 0 на VTY/console. Junos: set system login idle-timeout 10.",
         lambda f: f["exec_timeout_set"],
         objects=lambda f: [f"line {b} — без exec-timeout" for b in f.get("line_blocks_present", [])]),
    Rule("A4", CAT_ACCESS, "critical",
         "Используется обратимо шифруемый пароль (type 7)",
         "Пароль type 7 (Cisco) расшифровывается любым онлайн-декодером за секунды.",
         "Заменить на secret (type 8/9).",
         lambda f: not f["weak_password_type7"]),
    Rule("A5", CAT_ACCESS, "low",
         "Баннер входа не настроен",
         "banner motd (Cisco) / message (Junos) не найден.",
         "Cisco: banner motd. Junos: set system login message.",
         lambda f: f["banner_configured"]),
    Rule("A6", CAT_ACCESS, "medium",
         "HTTP-сервер управления включён",
         "ip http server / web-management найден в конфиге — лишняя незашифрованная (или менее проверенная) плоскость атаки.",
         "Cisco: no ip http server, no ip http secure-server (если не используется). Junos: убрать set system services web-management.",
         lambda f: not f["http_server_enabled"],
         objects=lambda f: list(f.get("http_server_raw_lines", []))),
    Rule("A7", CAT_ACCESS, "high",
         "SNMP community v2c активна",
         "Community-строка v2c найдена в конфиге — читается открытым текстом, часто дефолтная (public/private).",
         "Cisco: no snmp-server community public/private, перейти на snmp-server group ... v3 priv. Junos: убрать snmp community, настроить snmp v3.",
         lambda f: not f["snmp_v2c_enabled"],
         objects=lambda f: [f"community: {c}" for c in f.get("snmp_community_strings", [])]),
    Rule("A8", CAT_ACCESS, "medium",
         "NTP не настроен",
         "ntp server (Cisco) / ntp ... server (Junos) не найден — часы могут разойтись.",
         "Cisco: ntp server <ip>. Junos: set system ntp server <ip>.",
         lambda f: f["ntp_configured"]),
    Rule("A9", CAT_ACCESS, "high",
         "Syslog не отправляется на центральный сервер",
         "logging host / syslog host не найден — события устройства нигде не централизуются.",
         "Cisco: logging host <ip> + logging trap notifications. Junos: set system syslog host <ip>.",
         lambda f: f["syslog_host_configured"]),
    Rule("A10", CAT_ACCESS, "low",
         "Hostname похож на заводской",
         "hostname вида Switch1/Router1 — устройство не идентифицировано осмысленно.",
         "Задать содержательный hostname по соглашению об именовании площадки.",
         lambda f: not f.get("hostname_is_default", False),
         objects=lambda f: [f"hostname: {f['hostname_raw']}"] if f.get("hostname_raw") else []),

    # --- Резервирование (L3) — условные, см. applies ---
    Rule("C1", CAT_L3, "critical",
         "HSRP/VRRP без аутентификации",
         "Group standby/vrrp-group настроена без authentication — сосед в сегменте может перехватить роль active.",
         "Cisco: standby <N> authentication md5 key-string <ключ>. Junos: set ... vrrp-group authentication-key.",
         lambda f: f["hsrp_auth_configured"], applies=lambda f: f["hsrp_configured"]),
    Rule("C2", CAT_L3, "high",
         "Приоритет/preempt резервирующего протокола не заданы явно",
         "standby priority/preempt (или vrrp priority/preempt) отсутствуют — поведение при отказе не детерминировано.",
         "Cisco: standby <N> priority 110 + standby <N> preempt. Junos: priority + preempt в vrrp-group.",
         lambda f: f["hsrp_priority_set"] and f["hsrp_preempt_set"], applies=lambda f: f["hsrp_configured"]),
    Rule("C3", CAT_L3, "high",
         "Приоритет STP root не задан явно",
         "Значение приоритета — заводское (32768), root bridge может уехать на случайный коммутатор.",
         "Cisco: spanning-tree vlan <x> priority 4096 на обоих узлах ядра. Junos: set protocols rstp bridge-priority.",
         lambda f: f["stp_priority_set"]),
    Rule("C4", CAT_L3, "critical",
         "Аутентификация протокола маршрутизации не настроена",
         "OSPF/BGP сосед принимается без пароля/MD5 — подмена маршрутной информации возможна с любого сегмента, видящего порт.",
         "Cisco: ip ospf authentication message-digest / neighbor <x> password (BGP). Junos: authentication на interface/group.",
         lambda f: (not f["ospf_configured"] or f["ospf_auth_configured"]) and (not f["bgp_configured"] or f["bgp_auth_configured"]),
         applies=lambda f: f["ospf_configured"] or f["bgp_configured"]),
    Rule("C5", CAT_L3, "high",
         "LACP/агрегация не обнаружена на аплинках",
         "channel-group mode active / 802.3ad не найден — резервный аплинк, если физически есть, не агрегирован.",
         "Cisco: channel-group <n> mode active на обоих линках. Junos: ae-интерфейс с 802.3ad ether-options.",
         lambda f: f["lacp_configured"]),
    Rule("C6", CAT_L3, "medium",
         "Control-Plane Policing не настроен",
         "CPU устройства не защищён политикой CoPP от флуда управляющего трафика.",
         "Cisco: control-plane + service-policy input <copp-policy>. Junos: firewall filter на lo0 через policer.",
         lambda f: f["copp_configured"]),
    Rule("C7", CAT_L3, "medium",
         "max-prefix на eBGP-соседях не ограничен",
         "neighbor maximum-prefix не найден — некорректный анонс от соседа может исчерпать таблицу маршрутизации.",
         "Cisco: neighbor <x> maximum-prefix <n>. Junos: prefix-limit в family inet unicast группы BGP.",
         lambda f: f["bgp_maxprefix_set"], applies=lambda f: f["bgp_configured"]),

    # --- L2-доступ — условные, только если вообще есть access/trunk-порты ---
    Rule("L1", CAT_L2, "critical",
         "Port-security не настроен на access-портах",
         "switchport port-security не найден — количество MAC на порту ничем не ограничено.",
         "Cisco: switchport port-security + maximum 2 + violation restrict. Junos: mac-limit в secure-access-port.",
         lambda f: f["port_security_configured"] and f["port_security_maxmac_set"], applies=lambda f: f["access_ports_present"]),
    Rule("L3", CAT_L2, "high",
         "Native VLAN на транке не изменён с VLAN 1",
         "switchport trunk native vlan не переопределён — VLAN 1 неявно общий между всеми трансками.",
         "Cisco: switchport trunk native vlan <не 1>. Junos: native-vlan-id <x>.",
         lambda f: f["native_vlan_changed"], applies=lambda f: f["trunk_present"]),
    Rule("L4", CAT_L2, "medium",
         "Разрешённые VLAN на транке не ограничены явно",
         "switchport trunk allowed vlan не задан — по умолчанию пропускаются все VLAN.",
         "Cisco: switchport trunk allowed vlan <список>. Junos: vlan members [список].",
         lambda f: f["allowed_vlan_explicit"], applies=lambda f: f["trunk_present"]),
    Rule("L5", CAT_L2, "high",
         "BPDU/Loop Guard не настроена ни на одном порту",
         "spanning-tree bpduguard enable / guard loop (Cisco) или bpdu-block-on-edge (Junos) не найдено — риск петель/поддельного root bridge.",
         "Cisco: spanning-tree bpduguard enable на access-портах. Junos: bpdu-block-on-edge под edge-интерфейсами.",
         lambda f: f["stp_guard_configured"]),
    Rule("L6", CAT_L2, "medium",
         "Storm control не настроен",
         "storm-control broadcast/multicast/unicast level не найден — широковещательный шторм не ограничивается на порту.",
         "Cisco: storm-control broadcast level <x> (аналогично multicast/unicast). Junos: storm-control-profiles.",
         lambda f: f["storm_control_configured"], applies=lambda f: f["access_ports_present"]),
    Rule("L7", CAT_L2, "critical",
         "DHCP snooping не настроен",
         "ip dhcp snooping / dhcp-security не найден — поддельный DHCP-сервер в сегменте не блокируется.",
         "Cisco: ip dhcp snooping + ip dhcp snooping vlan <x> + trust на uplink. Junos: forwarding-options dhcp-security.",
         lambda f: f["dhcp_snooping_configured"], applies=lambda f: f["access_ports_present"]),

    # --- Гигиена конфигурации ---
    Rule("H2", CAT_HYGIENE, "low",
         "Небезопасные вспомогательные сервисы включены",
         "finger / bootp server / tcp-small-servers явно включены в конфиге.",
         "Cisco: no service finger, no ip bootp server, no service tcp-small-servers.",
         lambda f: not (f["finger_enabled"] or f["bootp_server_enabled"] or f["small_servers_enabled"])),
    Rule("H4", CAT_HYGIENE, "medium",
         "IP source-routing включён",
         "ip source-route явно разрешён — отправитель может задавать маршрут пакета сам, классический вектор обхода ACL.",
         "Cisco: no ip source-route.",
         lambda f: not f["source_route_enabled"]),
    Rule("H5", CAT_HYGIENE, "low",
         "Proxy-ARP явно не отключён",
         "На Cisco IOS proxy-ARP включён на интерфейсе по умолчанию — явного no ip proxy-arp в конфиге не найдено.",
         "Cisco: no ip proxy-arp на интерфейсах доступа, где не требуется. Junos: policy-options ... no-proxy-arp.",
         lambda f: f["proxy_arp_explicitly_disabled"]),
]
